esphome:
  name: "apollo-h-2"
  friendly_name: Apollo H-2
  comment: Apollo H-2
  name_add_mac_suffix: true
  platformio_options:
    board_build.flash_mode: dio

  project:
    name: "ApolloAutomation.H-2"
    version: "${version}"

  min_version: 2023.11.1
  on_boot:
    - priority: 500
      then:
        - lambda: |-
            id(deep_sleep_1).set_sleep_duration(id(deep_sleep_sleep_duration).state * 60 * 60 * 1000);
        - if:
            condition:
              or:
                - binary_sensor.is_on: ota_mode
                - switch.is_on: prevent_sleep
            then:
              - lambda: |- 
                  ESP_LOGW("Apollo", "Preventing Deep Sleep Due To OTA On Boot");
                  id(deep_sleep_1).prevent_deep_sleep(); 
    # Check button states for powered-off scenario
    - priority: -100
      then:
      - lambda: |-
          uint64_t wake = esp_sleep_get_ext1_wakeup_status();
          
          // Only process deep sleep wake if we actually woke from deep sleep
          if (wake != 0) {
            uint32_t low = wake % 0xFFFFFFFF;
            uint32_t high = (wake >> 32) % 0xFFFFFFFF;
            
            ESP_LOGI("Apollo", "Deep sleep wake detected, wake status: 0x%llx", wake);
            
            // Check which song button caused the wake-up
            if ((low) & (1<<(4))) {
              id(wakeup_button_pressed).publish_state("1");
              id(btn_play_song_1).press();
            }
            else if ((low) & (1<<(5))) {
              id(wakeup_button_pressed).publish_state("2");
              id(btn_play_song_2).press();
            }
            else if ((low) & (1<<(6))) {
              id(wakeup_button_pressed).publish_state("3");
              id(btn_play_song_3).press();
            }
            else if ((low) & (1<<(7))) {
              id(wakeup_button_pressed).publish_state("4");
              id(btn_play_song_4).press();
            }
            else {
              id(wakeup_button_pressed).publish_state("0");
            }
          }
          else {
            // If no deep sleep wake and no button was detected in powered-off scenario
            // then set to "0" (no button press)
            if (id(wakeup_button_pressed).state == "") {
              ESP_LOGI("Apollo", "No wake source detected, setting to 0");
              id(wakeup_button_pressed).publish_state("0");
            }
          }
    - priority: -10
      then:
        - if:
            condition:
              - lambda: "return id(runTest);"
            then:
              - lambda: "id(testScript).execute();"
  on_shutdown:
    - light.turn_off: rgb_light

dashboard_import:
  package_import_url: github://ApolloAutomation/H-2/Integrations/ESPHome/H-2.yaml
  import_full_config: false

improv_serial:

esp32_improv:
  authorizer: none

ota:
  - platform: esphome
    id: ota_esphome
  - platform: http_request
    id: ota_managed

http_request:
  verify_ssl: true

safe_mode:

update:
  - platform: http_request
    id: firmware_update
    name: Firmware Update
    source: https://apolloautomation.github.io/H-2/firmware2/manifest.json

wifi:
  on_connect:
    - delay: 5s
    - ble.disable:
  on_disconnect:
    - ble.enable:
  ap:
    ssid: "Apollo H2 Hotspot"

logger:

captive_portal:

web_server:
  version: 3
  port: 80

external_components:
  - source: github://ApolloAutomation/ExternalComponents
    components: [deep_sleep]
    
api:
  services:
    - service: play_buzzer
      variables:
        song_str: string
      then:
        - rtttl.play:
            rtttl: !lambda 'return song_str;'
    - service: play_song_1
      then:
        - script.execute: play_song_1
    - service: play_song_2
      then:
        - script.execute: play_song_2
    - service: play_song_3
      then:
        - script.execute: play_song_3
    - service: play_song_4
      then:
        - script.execute: play_song_4
  reboot_timeout: 0s
  on_client_connected:
    then:
      - delay: 5s
      - if:
          condition:
            or:
              - binary_sensor.is_on: ota_mode
              - switch.is_on: prevent_sleep
          then:
            - lambda: |- 
                ESP_LOGW("Apollo", "Preventing Deep Sleep Due To OTA Or Switch");
                id(deep_sleep_1).prevent_deep_sleep();
      - component.update: wakeup_button_pressed
switch:
  - platform: template
    name: "Prevent Sleep"
    id: prevent_sleep
    icon: mdi:sleep
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: true
    entity_category: "config"
    on_turn_on:
      then:
        - lambda: |- 
            id(deep_sleep_1).prevent_deep_sleep();
    on_turn_off:
      then:
        - if:
            condition:
              binary_sensor.is_off: ota_mode
            then:
              - lambda: |- 
                  id(deep_sleep_1).allow_deep_sleep();

binary_sensor:
  - platform: status
    name: Online
    id: ink_ha_connected
  - platform: homeassistant
    name: "OTA Mode"
    id: ota_mode
    entity_id: input_boolean.apollo_ota_mode
    on_press:
      then:
        - lambda: |-
            id(deep_sleep_1).prevent_deep_sleep();
    on_release:  
      then:
        - if:
            condition:
              switch.is_off: prevent_sleep
            then:
              - lambda: |-
                  id(deep_sleep_1).allow_deep_sleep();

sensor:
  - platform: wifi_signal
    name: RSSI
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

script:
  - id: statusCheck
    then:
      - if:
          condition:
            - lambda: 'return id(ink_ha_connected).state;'
          then:
            - logger.log: "Apollo Automation: Connected To HA"
            - light.turn_on: 
                id: rgb_light
                brightness: 40%
                red: 0%
                green: 0%
                blue: 100%
          else:
            - if:
                condition:
                  - wifi.connected
                then:
                  - logger.log: "Apollo Automation: Connected To Wifi"
                  - light.turn_on: 
                      id: rgb_light
                      brightness: 40%
                      red: 0%
                      green: 100%
                      blue: 0%
                else:
                  - logger.log: "Apollo Automation: Not Connected To Wifi"
                  - light.turn_on: 
                      id: rgb_light
                      brightness: 40%
                      red: 100%
                      green: 100%
                      blue: 0%
      - delay: 5s
      - light.turn_off: rgb_light
  - id: ShouldSleep
    then:
      - if:
          condition:
            or:
              - binary_sensor.is_on: ota_mode
              - switch.is_on: prevent_sleep
          then:
            - lambda: |-
                ESP_LOGW("Apollo", "Preventing Deep Sleep Due To OTA On Boot");
                id(deep_sleep_1).prevent_deep_sleep();
          else: 
            - deep_sleep.enter:
                id: deep_sleep_1


packages:
  core: !include Core.yaml
